[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.3.0", default-features = false, features = ['std'] }
serde = { version = "1.0", default-features = false, features = ["derive"] }