// config/SpaceshipConfigs.ts
import { SpaceshipProperties } from "../types/SpaceshipTypes";

export const spaceshipConfigs: Record<string, SpaceshipProperties> = {
  default: {
    shape: "triangle",
    size: 1.0,
    transparency: 1.0,
    primaryColor: "#FF007F",
    secondaryColor: "#FF007F",
    glowColor: "#FF007F",
    outline: {
      enabled: true,
      color: "#FF007F",
      thickness: 2,
      glowIntensity: 0.8,
    },
    surfacePattern: "none",
    patternOpacity: 0,
    patternAnimation: "static",
    trail: {
      enabled: true,
      type: "particles",
      color: "#FFFFFF",
      length: 45,
      fadeSpeed: 0.2,
      particleCount: 3,
    },
    companions: {
      enabled: false,
      count: 0,
      type: "drones",
      size: 0,
      orbitDistance: 0,
      orbitSpeed: 0,
      formation: "circular",
    },
    specialEffects: {
      cloaking: false,
      targeting: false,
      morphing: false,
      energyField: false,
      crown: false,
      wings: false,
      horns: false,
      aura: false,
    },
    weapon: {
      type: "energy",
      color: "#FF9D00",
      chargeEffect: false,
      muzzleFlash: false,
      damage: 1,
      bulletCount: 1,
      fireRate: 1,
    },
  },
  technical: {
    shape: "angular",
    size: 1.0,
    transparency: 1.0,
    primaryColor: "#00FFFF",
    secondaryColor: "#0080FF",
    glowColor: "#00FFFF",
    outline: {
      enabled: true,
      color: "#00FFFF",
      thickness: 2,
      glowIntensity: 0.8,
    },
    surfacePattern: "circuits",
    patternOpacity: 0.7,
    patternAnimation: "flowing",
    trail: {
      enabled: true,
      type: "code",
      color: "#00FFFF",
      length: 50,
      fadeSpeed: 0.1,
      particleCount: 20,
    },
    companions: {
      enabled: false,
      count: 0,
      type: "drones",
      size: 0,
      orbitDistance: 0,
      orbitSpeed: 0,
      formation: "circular",
    },
    specialEffects: {
      cloaking: false,
      targeting: true,
      morphing: false,
      energyField: false,
      crown: false,
      wings: false,
      horns: false,
      aura: false,
    },
    weapon: {
      type: "laser",
      color: "#00FFFF",
      chargeEffect: true,
      muzzleFlash: true,
      damage: 2,
      bulletCount: 1,
      fireRate: 1.2,
    },
  },
  social: {
    shape: "fluid",
    size: 1.0,
    transparency: 1.0,
    primaryColor: "#FF00FF",
    secondaryColor: "#8000FF",
    glowColor: "#FF00FF",
    outline: {
      enabled: true,
      color: "#FF00FF",
      thickness: 2,
      glowIntensity: 0.9,
    },
    surfacePattern: "spirals",
    patternOpacity: 0.8,
    patternAnimation: "morphing",
    trail: {
      enabled: true,
      type: "particles",
      color: "#FF00FF",
      length: 40,
      fadeSpeed: 0.15,
      particleCount: 15,
    },
    companions: {
      enabled: false,
      count: 0,
      type: "drones",
      size: 0,
      orbitDistance: 0,
      orbitSpeed: 0,
      formation: "circular",
    },
    specialEffects: {
      cloaking: false,
      targeting: false,
      morphing: true,
      energyField: false,
      crown: false,
      wings: false,
      horns: false,
      aura: false,
    },
    weapon: {
      type: "energy",
      color: "#FF00FF",
      chargeEffect: true,
      muzzleFlash: false,
      damage: 1,
      bulletCount: 2,
      fireRate: 0.8,
    },
  },
  crew: {
    shape: "enlarged",
    size: 1.3,
    transparency: 1.0,
    primaryColor: "#00FF80",
    secondaryColor: "#80FF00",
    glowColor: "#00FF80",
    outline: {
      enabled: true,
      color: "#00FF80",
      thickness: 2,
      glowIntensity: 0.7,
    },
    surfacePattern: "none",
    patternOpacity: 0,
    patternAnimation: "static",
    trail: {
      enabled: true,
      type: "particles",
      color: "#00FF80",
      length: 30,
      fadeSpeed: 0.2,
      particleCount: 10,
    },
    companions: {
      enabled: true,
      count: 3,
      type: "drones",
      size: 0.4,
      orbitDistance: 60,
      orbitSpeed: 1.0,
      formation: "triangular",
    },
    specialEffects: {
      cloaking: false,
      targeting: false,
      morphing: false,
      energyField: false,
      crown: false,
      wings: false,
      horns: false,
      aura: false,
    },
    weapon: {
      type: "energy",
      color: "#00FF80",
      chargeEffect: false,
      muzzleFlash: true,
      damage: 1,
      bulletCount: 3,
      fireRate: 1.5,
    },
  },
  solo: {
    shape: "ghostly",
    size: 1.0,
    transparency: 0.6,
    primaryColor: "#FF0040",
    secondaryColor: "#800020",
    glowColor: "#FF0040",
    outline: {
      enabled: true,
      color: "#FF0040",
      thickness: 1,
      glowIntensity: 0.5,
    },
    surfacePattern: "shadow",
    patternOpacity: 0.6,
    patternAnimation: "flickering",
    trail: {
      enabled: true,
      type: "shadow",
      color: "#FF0040",
      length: 20,
      fadeSpeed: 0.3,
      particleCount: 8,
    },
    companions: {
      enabled: false,
      count: 0,
      type: "drones",
      size: 0,
      orbitDistance: 0,
      orbitSpeed: 0,
      formation: "circular",
    },
    specialEffects: {
      cloaking: true,
      targeting: false,
      morphing: false,
      energyField: false,
      crown: false,
      wings: false,
      horns: false,
      aura: false,
    },
    weapon: {
      type: "shadow",
      color: "#FF0040",
      chargeEffect: false,
      muzzleFlash: false,
      damage: 3,
      bulletCount: 1,
      fireRate: 2.0,
    },
  },
  systemController: {
    shape: "angular",
    size: 2.0,
    transparency: 1.0,
    primaryColor: "#00FFFF",
    secondaryColor: "#FFFFFF",
    glowColor: "#00FFFF",
    outline: {
      enabled: true,
      color: "#00FFFF",
      thickness: 4,
      glowIntensity: 1.0,
    },
    surfacePattern: "circuits",
    patternOpacity: 1.0,
    patternAnimation: "flowing",
    trail: {
      enabled: false,
      type: "none",
      color: "",
      length: 0,
      fadeSpeed: 0,
      particleCount: 0,
    },
    companions: {
      enabled: false,
      count: 0,
      type: "drones",
      size: 0,
      orbitDistance: 0,
      orbitSpeed: 0,
      formation: "circular",
    },
    specialEffects: {
      cloaking: false,
      targeting: false,
      morphing: false,
      energyField: true,
      crown: false,
      wings: false,
      horns: false,
      aura: false,
    },
    weapon: {
      type: "quantum",
      color: "#00FFFF",
      chargeEffect: true,
      muzzleFlash: true,
      damage: 5,
      bulletCount: 2.2,
      fireRate: 2.5,
    },
  },
  digitalGod: {
    shape: "fluid",
    size: 1.5,
    transparency: 0.8,
    primaryColor: "#FFFFFF",
    secondaryColor: "#FFD700",
    glowColor: "#FFFFFF",
    outline: {
      enabled: true,
      color: "#FFFFFF",
      thickness: 6,
      glowIntensity: 1.5,
    },
    surfacePattern: "none",
    patternOpacity: 0,
    patternAnimation: "static",
    trail: {
      enabled: true,
      type: "energy",
      color: "#FFFFFF",
      length: 100,
      fadeSpeed: 0.05,
      particleCount: 50,
    },
    companions: {
      enabled: false,
      count: 0,
      type: "drones",
      size: 0,
      orbitDistance: 0,
      orbitSpeed: 0,
      formation: "circular",
    },
    specialEffects: {
      cloaking: false,
      targeting: false,
      morphing: true,
      energyField: true,
      crown: false,
      wings: false,
      horns: false,
      aura: true,
    },
    weapon: {
      type: "quantum",
      color: "#FFFFFF",
      chargeEffect: true,
      muzzleFlash: false,
      damage: 8,
      bulletCount: 1,
      fireRate: 3.0,
    },
  },
  criminalEmperor: {
    shape: "enlarged",
    size: 2.5,
    transparency: 1.0,
    primaryColor: "#FFD700",
    secondaryColor: "#FF8000",
    glowColor: "#FFD700",
    outline: {
      enabled: true,
      color: "#FFD700",
      thickness: 3,
      glowIntensity: 1.2,
    },
    surfacePattern: "none",
    patternOpacity: 0,
    patternAnimation: "static",
    trail: {
      enabled: true,
      type: "particles",
      color: "#FFD700",
      length: 60,
      fadeSpeed: 0.1,
      particleCount: 30,
    },
    companions: {
      enabled: true,
      count: 12,
      type: "fleet",
      size: 0.3,
      orbitDistance: 100,
      orbitSpeed: 0.5,
      formation: "scattered",
    },
    specialEffects: {
      cloaking: false,
      targeting: false,
      morphing: false,
      energyField: false,
      crown: true,
      wings: false,
      horns: false,
      aura: false,
    },
    weapon: {
      type: "energy",
      color: "#FFD700",
      chargeEffect: true,
      muzzleFlash: true,
      damage: 4,
      bulletCount: 5,
      fireRate: 1.8,
    },
  },
  overlord: {
    shape: "angular",
    size: 2.2,
    transparency: 1.0,
    primaryColor: "#8B0000",
    secondaryColor: "#FF0000",
    glowColor: "#FF0000",
    outline: {
      enabled: true,
      color: "#FF0000",
      thickness: 4,
      glowIntensity: 1.4,
    },
    surfacePattern: "demonic",
    patternOpacity: 1.0,
    patternAnimation: "pulsing",
    trail: {
      enabled: true,
      type: "chaos",
      color: "#FF0000",
      length: 75,
      fadeSpeed: 0.07,
      particleCount: 38,
    },
    companions: {
      enabled: false,
      count: 0,
      type: "drones",
      size: 0,
      orbitDistance: 0,
      orbitSpeed: 0,
      formation: "circular",
    },
    specialEffects: {
      cloaking: false,
      targeting: false,
      morphing: false,
      energyField: true,
      crown: true,
      wings: false,
      horns: true,
      aura: false,
    },
    weapon: {
      type: "chaos",
      color: "#FF0000",
      chargeEffect: true,
      muzzleFlash: true,
      damage: 10,
      bulletCount: 3,
      fireRate: 2.2,
    },
  },
};
